name: build

on: [push, pull_request]

jobs:
  upload-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Upload dummy
        uses: actions/upload-artifact@v2
        with:
          name: dummy1
          path: dummy1.zip
  publish-s3-artifact:
    runs-on: ubuntu-latest
    needs: upload-to-github
    steps:
      - uses: actions/checkout@v2
      - name: Upload to S3 as artifact
        uses: ./
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          DIST_FILE_PATH: './dummy91.zip'      # optional: defaults to entire repository
  trigger-cd:
    runs-on: ubuntu-latest
    needs: upload-to-github
    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          data: "{'deployment': 'finished', 'project': 'actions', 'runid':$GITHUB_RUN_ID}"
  dummy-fake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Verify run id
        run : echo Run Id $GITHUB_RUN_ID

